### ISSUE TITLE
Add Ingress functionality for Kubernetes 1.22

### ISSUE THREAD

**Issue by malliachris** [saturnwire/plex-helm-chart#1]
Hello there. I've been using your well made Plex helm chart for a couple of months now, but I see that it's been made for an older K8s API version - specifically, the Ingress template is incompatible for Kubernetes v1.22.x

As a thank you for your work, I've already compiled and tested a fix for the Ingress template - but I was unable to publish the branch to your repo. Here are the amendments that I'm proposing:

Ingress template:

```
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "plex.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $kubeVersion := .Capabilities.KubeVersion.Minor -}}

{{- if ge $kubeVersion "22"  -}}
apiVersion: networking.k8s.io/v1
{{- else if ge $kubeVersion "14" -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "plex.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
        {{- range .paths }}
        - path: {{ .path | quote }}
          {{ if ge $kubeVersion "22"  -}}
          pathType: {{ .pathType }}
          backend:
            service:
              name: {{ $fullName }}
              port:
                number: {{ $svcPort }}
          {{- else -}}
          backend:
            serviceName: {{ $fullName }}
            servicePort: {{ $svcPort }}
          {{- end }}
        {{- end }}
  {{- end }}
{{- end }}
```

Modifications to values file:

```
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: 
        - path: []
          pathType: []
          # pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
```

I've tested this setup to work on my cluster without TLS config. Specifically, a single node Ubuntu  host with a K3s setup (using Traefik).

As mentioned, I've already compiled these changes into a branch - so if you're interested, just provide me access to the repo and I'll raise you a PR with my branch.
